// ── Seed data ────────────────────────────────────────────────────
//
// Exact transcription of every hardcoded section from:
//   app/home-view.jsx      (11 sections)
//   app/about/about-view.jsx (6 sections)
//   app/services/services-view.jsx (6 sections)
//   app/contact/contact-view.jsx (3 sections)
//
// Each entry is a page_sections row minus id/timestamps (generated by seed script).
// The script (scripts/seed-sections.mjs) reads this, clears existing rows for
// these pages, and inserts them fresh — idempotent.
//
// IMPORTANT: every value is fully self-contained here — no section depends
// on in-code fallbacks (faq-data.js, hero URL defaults, etc.), so deleting
// those files after seeding cannot break the public pages.

// ── Inline FAQ sets (formerly in lib/faq-data.js) ────────────────
const HOME_FAQS = [
  { question: 'What areas does Hayagriva Interiors serve?', answer: 'We are based in Maddilapalem, Visakhapatnam, and design interiors for homes and commercial spaces across Andhra Pradesh. For larger turnkey projects, we can travel beyond the region — just reach out and we will confirm coverage for your location.' },
  { question: 'Do you offer a free design consultation?', answer: 'Yes. Your first design consultation is completely complimentary. Book a session and our lead designers will review your space, discuss your goals and budget, and walk you through material samples before any commitment.' },
  { question: 'What is the typical timeline for a full home interior project?', answer: 'A complete turnkey home interior usually takes 45 to 90 days from design approval to handover, depending on scope. We share a detailed milestone schedule up front so you always know what happens next.' },
  { question: 'Can I see examples of your past work before I decide?', answer: 'Absolutely. Head over to our Portfolio page to explore completed kitchens, bedrooms, and living rooms, or use the Before/After slider on our home page to see the transformation from an empty shell to a finished space.' },
  { question: 'How do I get started with Hayagriva Interiors?', answer: 'Simply fill out the lead form on this page or visit our Contact page. Our coordinator will call you back within 24 hours to schedule your free consultation and gather the details we need to begin.' }
]

const ABOUT_FAQS = [
  { question: 'How long has Hayagriva Interiors been in business?', answer: 'Hayagriva Interiors is a boutique studio with over 5 years of experience designing and executing luxury residential interiors. In that time we have delivered 500+ homes across Andhra Pradesh with a focus on craftsmanship and material honesty.' },
  { question: 'What is your design philosophy?', answer: 'We believe interiors should feel personal and timeless. Every project balances modern architecture with bespoke joinery — listening closely to your spatial habits, drafting precise plans, and overseeing manufacture so the result is both beautiful and built to last.' },
  { question: 'Do you have an in-house team or do you outsource?', answer: 'Our designers, carpenters, and project managers are all part of one in-house team. This keeps quality consistent, timelines tight, and a single point of accountability from the first sketch to the final handover.' },
  { question: 'Can I visit your studio to see material samples?', answer: 'Yes. Drop by our Maddilapalem studio to browse our catalog of woods, marbles, veneers, and upholstery fabrics. A hands-on look at materials is the best way to finalize your finishes before we begin production.' },
  { question: 'Do you take on commercial or office projects?', answer: 'We do. While our focus is residential sanctuaries, we also design refined workspaces, retail interiors, and office fitouts using the same premium materials and ergonomic standards.' }
]

const SERVICES_FAQS = [
  { question: 'How much do interior design services cost?', answer: 'Pricing depends on scope and material choices. As a guide: modular kitchens start from ₹1.5L–₹5L, bedrooms ₹80K–₹3L, and living rooms ₹1L–₹4L. Full turnkey interiors typically range from ₹3L–₹25L. We share a transparent estimate after your first consultation.' },
  { question: 'What services do you offer?', answer: 'We offer modular kitchens, bedroom interiors, living room design, space planning & 3D design, complete turnkey interiors, and renovation. Each service can be booked standalone or combined into a full-home package.' },
  { question: 'Do you provide 3D designs before execution?', answer: 'Yes. Our Space Planning & 3D Design service delivers photorealistic renders of every room before a single material is ordered. You will see finishes, furniture scale, and lighting from every angle, with unlimited revisions until you are satisfied.' },
  { question: 'Can you renovate my existing home without a full rebuild?', answer: 'Definitely. Our renovation service covers structural modifications, kitchen and bathroom makeovers, flooring and plumbing upgrades, electrical rewiring, and complete aesthetic overhauls — with phased execution to minimise disruption.' },
  { question: 'Are materials and hardware of good quality?', answer: 'We use only premium materials — moisture-resistant plywood, natural stone countertops, solid wood veneers, and trusted soft-close hardware — backed by quality checks at every milestone of the build.' }
]

const PORTFOLIO_FAQS = [
  { question: 'What types of projects are in your portfolio?', answer: 'Our portfolio showcases completed kitchens, bedrooms, and living rooms, plus full-home turnkey projects and renovations. Use the category filter above to view work specific to a single room type.' },
  { question: 'Can I get a design similar to a project I see here?', answer: 'Yes. Every project we show is bespoke, but we can adapt layouts, color palettes, and material choices to your space. Share the project you love during your consultation and we will tailor it to your home and budget.' },
  { question: 'How can I see a project in person?', answer: 'Some clients are happy to host studio visits to completed homes — just ask during your consultation and we will arrange a walkthrough where possible, or bring you to our Maddilapalem studio for material samples.' },
  { question: 'Are the photos on the site real client homes?', answer: 'Yes. The images in our portfolio are photographs of actual homes we have delivered, styled for handover. What you see is the standard of finish you can expect from a Hayagriva project.' },
  { question: 'Do you have before and after comparisons?', answer: 'We do. Use the Before/After slider on this page to compare an empty measurement shell with our finished bespoke interior, and see firsthand the transformation our team delivers.' }
]

const CONTACT_FAQS = [
  { question: 'How can I book a consultation?', answer: 'Fill out the form on this page, call us at +91 95731 78887, or email interiorsbyhayagriva@gmail.com. Our coordinator will respond within 24 hours to schedule your free design consultation.' },
  { question: 'Where is your studio located?', answer: 'Our studio is on the second floor of DR DEEN COMPLEX, 51-15-1/6, opposite Tech Mahindra, Satyam Junction, KRANTHI NAGAR, Maddilapalem, Visakhapatnam, Andhra Pradesh 530013. Click the address to open it in Google Maps.' },
  { question: 'What are your working hours?', answer: 'We are open Monday to Saturday, 9:30 AM to 7:00 PM. Consultations are by appointment so we can give your project the focused attention it deserves.' },
  { question: 'Is the first consultation really free?', answer: 'Yes. Your first design consultation is complimentary with no obligation. We will review your space, discuss your goals and budget, and walk you through samples before you decide to move forward.' },
  { question: 'Do you respond on WhatsApp?', answer: 'We do. Tap the floating WhatsApp button on any page to chat with us directly, or message us at +91 95731 78887 and we will reply during working hours.' }
]

export const HOME_SECTIONS = [
  {
    page: 'home',
    type: 'hero',
    title: 'Transform Your Home into a',
    subtitle: 'Luxury Turnkey Interiors',
    description: 'Bespoke layouts, premium materials, and flawless execution. We translate your story into tailored residential sanctuaries.',
    layout: 'full-width',
    images: [{ url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=1800&auto=format&fit=crop' }],
    buttons: [
      { text: 'Book Free Consultation', link: '#consultation' },
      { text: 'View Portfolio', link: '/portfolio' }
    ],
    custom_json: {
      titleAccent: 'Dream Space.',
      showLeadForm: true
    },
    is_visible: true,
    section_order: 0
  },
  {
    page: 'home',
    type: 'stats',
    title: '',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {
      items: [
        { value: 500, suffix: '+', label: 'Homes Delivered', subtext: 'Exquisite designs across AP', icon: 'CheckCircle2' },
        { value: 5, suffix: '+ Years', label: 'Experience', subtext: 'Refined craftsmanship', icon: 'Shield' },
        { value: 100, suffix: '%', label: 'Client Satisfaction', subtext: 'Discerning reviews', icon: 'Heart' }
      ]
    },
    is_visible: true,
    section_order: 1
  },
  {
    page: 'home',
    type: 'services-preview',
    title: 'Services We Specialize In',
    subtitle: 'Expert Design Studios',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {
      viewAllLink: '/services',
      items: [
        { title: 'Modular Kitchen', desc: 'Sleek, ergonomic layouts featuring premium soft-close cabinets, white oak paneling, and marble surfaces.', icon: 'Utensils', href: '/services/modular-kitchen' },
        { title: 'Bedroom Interiors', desc: 'Timeless master suites designed for peace. Custom headboards, walk-in closets, and ambient bedside lighting.', icon: 'Bed', href: '/services/bedroom' },
        { title: 'Living Room Design', desc: 'Elegant lounges blending Scandinavian simplicity and luxury. Floating media consoles and bespoke plaster walls.', icon: 'Sofa', href: '/services/living-room' },
        { title: 'Space Planning & 3D Design', desc: 'Professional space planning with photorealistic 3D renders to visualize your home before a single material is ordered.', icon: 'PencilRuler', href: '/services/space-planning' },
        { title: 'Turnkey Interiors', desc: 'Complete interior solutions from design to execution.', icon: 'KeyRound', href: '/services/turnkey-solutions' },
        { title: 'Renovation', desc: 'Revitalize your existing spaces with expert remodeling, structural upgrades, and aesthetic makeovers.', icon: 'Hammer', href: '/services/renovation' }
      ]
    },
    is_visible: true,
    section_order: 2
  },
  {
    page: 'home',
    type: 'process-timeline',
    title: 'Our Seamless Design Process',
    subtitle: 'The Turnkey Workflow',
    description: 'A refined, transparent journey from the first conversation to the final handover — crafted with care at every step.',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {
      steps: [
        { step: '01', title: 'Consultation', desc: 'We understand your needs, space, and budget to craft a clear vision for your project.', icon: 'ClipboardList' },
        { step: '02', title: 'Design & Planning', desc: 'We create detailed layouts, 3D designs, and execution-ready plans tailored to you.', icon: 'PencilRuler' },
        { step: '03', title: 'Material Selection', desc: 'Choose premium finishes, colors, and materials that match your aesthetic perfectly.', icon: 'Palette' },
        { step: '04', title: 'Execution', desc: 'Our skilled craftsmen bring the design to life with precision and supervision.', icon: 'Hammer' },
        { step: '05', title: 'Handover', desc: 'Final delivery with rigorous quality assurance and a flawless, ready-to-live space.', icon: 'KeyRound' }
      ],
      highlights: [
        { title: 'On-Time Delivery', desc: 'Projects delivered as promised', icon: 'Clock' },
        { title: 'Quality Assurance', desc: 'Rigorous checks at every stage', icon: 'ShieldCheck' },
        { title: 'Expert Team', desc: 'Skilled designers & craftsmen', icon: 'Users' },
        { title: 'End-to-End Support', desc: 'With you from concept to handover', icon: 'Headphones' }
      ]
    },
    is_visible: true,
    section_order: 3
  },
  {
    page: 'home',
    type: 'before-after',
    title: 'Witness the Difference',
    subtitle: 'Visual Transformation',
    description: 'Drag the center slider handle left or right to compare a raw site measurement shell with our finalized bespoke interior.',
    layout: 'full-width',
    images: [
      { url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=1200&auto=format&fit=crop', label: 'Before: Empty space shell' },
      { url: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?q=80&w=1200&auto=format&fit=crop', label: 'After: Luxury Bed Chamber' }
    ],
    buttons: [],
    custom_json: {
      beforeLabel: 'Before: Empty space shell',
      afterLabel: 'After: Luxury Bed Chamber'
    },
    is_visible: true,
    section_order: 4
  },
  {
    page: 'home',
    type: 'room-designs',
    title: 'Room-wise Inspirations',
    subtitle: 'Aesthetics by Room',
    description: 'Explore custom catalogs designed specifically for each room environment. Select a room below to filter our selected creations.',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {
      items: [
        { name: 'Kitchen', image: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?q=80&w=800&auto=format&fit=crop', filter: 'Kitchen', tag: 'Culinary Hubs' },
        { name: 'Bedroom', image: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?q=80&w=800&auto=format&fit=crop', filter: 'Bedroom', tag: 'Serene Sanctuary' },
        { name: 'Living Room', image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=800&auto=format&fit=crop', filter: 'Living Room', tag: 'Grand Lounge' }
      ]
    },
    is_visible: true,
    section_order: 5
  },
  {
    page: 'home',
    type: 'testimonials',
    title: 'What Our Clients Say',
    subtitle: 'Google Reviews',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {},
    is_visible: true,
    section_order: 6
  },
  {
    page: 'home',
    type: 'featured-projects',
    title: 'Selected Creations',
    subtitle: 'Portfolio Highlights',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {
      viewAllLink: '/portfolio',
      items: [
        { title: 'Modern Wood Kitchen & Island', type: 'Modular Kitchen', budget: '₹8.5 Lakhs', image: '/images/project-1.jpg', category: 'Kitchen', desc: 'Fine timber panels, bespoke configurations, custom layout styling.' },
        { title: 'Bespoke Master Wardrobe', type: 'Residential Fitout', budget: '₹12 Lakhs', image: '/images/project-2.jpg', category: 'Bedroom', desc: 'Fine timber panels, bespoke configurations, custom layout styling.' },
        { title: 'Japandi Living Lounge', type: 'Full Residence', budget: '₹22 Lakhs', image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=800&auto=format&fit=crop', category: 'Living Room', desc: 'Fine timber panels, bespoke configurations, custom layout styling.' }
      ]
    },
    is_visible: true,
    section_order: 7
  },
  {
    page: 'home',
    type: 'why-choose',
    title: 'Why Homeowners Trust Hayagriva',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: { variant: 'light', heading: 'Why Homeowners Trust Hayagriva' },
    is_visible: true,
    section_order: 8
  },
  {
    page: 'home',
    type: 'faq',
    title: 'Your Interior Design Questions, Answered',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: { variant: 'cream', items: HOME_FAQS },
    is_visible: true,
    section_order: 9
  },
  {
    page: 'home',
    type: 'cta',
    title: 'Ready to Transform Your Space?',
    subtitle: 'Design Consultation',
    description: 'Schedule a complimentary design session with our lead architects. We will prepare space blueprints, select material samples, and provide immediate project estimates.',
    layout: 'full-width',
    images: [],
    buttons: [{ text: 'Get Free Quote', link: '/contact' }],
    custom_json: { variant: 'full' },
    is_visible: true,
    section_order: 10
  }
]

export const ABOUT_SECTIONS = [
  {
    page: 'about',
    type: 'hero',
    title: 'Elegance, Craft, and a Signature',
    subtitle: 'Hayagriva Studio',
    description: 'We design luxury interiors that feel warm, modern, and deeply personal. Every residential project is built to reflect your story, with thoughtful layout details, premium finishes, and turnkey timeline execution.',
    layout: 'split',
    images: [{ url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=1200&auto=format&fit=crop', key: '' }],
    buttons: [
      { text: 'Work With Us', link: '/contact' },
      { text: 'View Portfolio', link: '/portfolio' }
    ],
    custom_json: {
      titleAccent: 'Design Approach.',
      showLeadForm: false
    },
    is_visible: true,
    section_order: 0
  },
  {
    page: 'about',
    type: 'about-story',
    title: 'A boutique studio rooted in craftsmanship, layout optimization, and material honesty.',
    subtitle: 'OUR JOURNEY',
    description: 'Hayagriva Interiors began with a desire to create residential sanctuaries that feel curated, calm, and unmistakably premium. We blend modern architecture with bespoke joinery, delivering homes that balance luxury with livability.\n\nOur approach is highly collaborative: we listen deeply to your spatial habits, draft precise plans, and oversee manufacture so the final result is both beautiful and built to last.',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {
      cards: [
        { label: 'MISSION', heading: 'Design homes that feel personal and timeless.', body: 'We create residential environments that elevate everyday rituals through intelligent layout configurations, layered lighting, and elegant joinery.' },
        { label: 'VISION', heading: 'The first choice for luxurious residential interiors.', body: 'We aspire to define new standards of premium home design across the region with every project we deliver, from conceptual sketches to key handover.' }
      ]
    },
    is_visible: true,
    section_order: 1
  },
  {
    page: 'about',
    type: 'why-choose',
    title: 'The Trusted Choice for Discerning Homeowners',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: { variant: 'light', heading: 'The Trusted Choice for Discerning Homeowners' },
    is_visible: true,
    section_order: 2
  },
  {
    page: 'about',
    type: 'design-journal',
    title: 'Bespoke Interior Insights',
    subtitle: 'DESIGN JOURNAL',
    description: "Read our principal designers' guides on material selections, layouts, lighting, and styling aesthetics.",
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {
      items: [
        { title: 'The Art of Japandi Minimalist Living', category: 'Aesthetics', date: 'June 12, 2026', image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=800&auto=format&fit=crop', desc: 'Discover how to balance raw Scandinavian warmth with quiet Japanese simplicity to create an uncluttered, modern sanctuary.', slug: 'art-of-japandi-minimalist-living' },
        { title: 'Ergonomic Modular Kitchen Guidelines', category: 'Engineering', date: 'May 28, 2026', image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop', desc: 'An in-depth look at counter heights, modular layout workflows, soft-close hardware configurations, and material selections.', slug: 'ergonomic-modular-kitchen-guidelines' },
        { title: 'Layered Illumination for Private Suites', category: 'Lighting', date: 'April 15, 2026', image: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?q=80&w=800&auto=format&fit=crop', desc: 'How to configure layered bedroom lighting using concealed warm coves, task spots, and smart dimming transitions.', slug: 'layered-illumination-private-suites' }
      ]
    },
    is_visible: true,
    section_order: 3
  },
  {
    page: 'about',
    type: 'faq',
    title: 'About Hayagriva Interiors',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: { variant: 'cream', items: ABOUT_FAQS },
    is_visible: true,
    section_order: 4
  },
  {
    page: 'about',
    type: 'cta',
    title: 'Ready to Design Your Haven?',
    subtitle: 'Design Consultation',
    description: 'Schedule a design session with our principal architects. We will discuss spatial blueprints, sample material palettes, and immediately compute customized site estimates.',
    layout: 'full-width',
    images: [],
    buttons: [{ text: 'Book Consultation', link: '/contact' }],
    custom_json: { variant: 'rounded' },
    is_visible: true,
    section_order: 5
  }
]

export const SERVICES_SECTIONS = [
  {
    page: 'services',
    type: 'services-grid',
    title: 'Curated Solutions for Your Home',
    subtitle: 'DESIGN SPECIALTIES',
    description: 'Click to explore room layouts designed to match your individual standard of daily comfort and luxurious spacing.',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {
      items: [
        { title: 'Modular Kitchen', desc: 'Precision cabinetry, natural stone countertops, and intelligent storage layouts.', image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=1000&auto=format&fit=crop', slug: 'modular-kitchen', filter: 'Kitchen' },
        { title: 'Bedroom Interiors', desc: 'Calm suites with luxury headboards, custom walk-in closets, and ambient lighting.', image: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?q=80&w=1000&auto=format&fit=crop', slug: 'bedroom', filter: 'Bedroom' },
        { title: 'Living Room Design', desc: 'Elegant lounges blending tailored furniture, floating consoles, and custom walls.', image: 'https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?q=80&w=1000&auto=format&fit=crop', slug: 'living-room', filter: 'Living Room' },
        { title: 'Space Planning & 3D Design', desc: 'Professional layouts with photorealistic renders before construction begins.', image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=1000&auto=format&fit=crop', slug: 'space-planning', filter: '' },
        { title: 'Turnkey Interiors', desc: 'Complete interior solutions from design to execution.', image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=1000&auto=format&fit=crop', slug: 'turnkey-solutions', filter: '' },
        { title: 'Renovation', desc: 'Revitalize your existing spaces with expert remodeling and structural upgrades.', image: 'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?q=80&w=1000&auto=format&fit=crop', slug: 'renovation', filter: '' }
      ]
    },
    is_visible: true,
    section_order: 0
  },
  {
    page: 'services',
    type: 'detailed-services',
    title: '',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {
      items: [
        { title: 'Modular Kitchen', tag: 'Culinary Engineering', desc: 'A high-performance kitchen designed around your workflow. We build custom modular setups incorporating premium soft-close drawer tracks, heavy-duty pull-out trays, and natural quartz countertops. Every cabinet and cabinet front is engineered to withstand daily use while presenting an immaculate, handleless aesthetic.', image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop', features: ['Custom modular layouts', 'Quartz & marble counters', 'Soft-close hardware', 'Under-cabinet illumination'] },
        { title: 'Bedroom Interiors', tag: 'Serene Sanctuaries', desc: 'Transform your bedroom into a quiet retreat. Our designers custom craft floor-to-ceiling headboards, integrated floating nightstands, and walk-in wardrobe organizers with matte finishes. Lighting is layered seamlessly using dimmable LED coves and directional task spotlights to transition spatial mood effortlessly.', image: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?q=80&w=1200&auto=format&fit=crop', features: ['Ergonomic wardrobe systems', 'Custom upholstered headboards', 'Layered mood coves', 'Space-optimizing layouts'] },
        { title: 'Living Room Design', tag: 'Grand Entertainment Lounges', desc: 'Bespoke living environments made for social gathering and quiet comfort alike. We specialize in floating entertainment consoles, wood-paneled feature walls, and hand-plastered textured finishes. Every piece of furniture is scaled and positioned to optimize both architectural flow and everyday comfort.', image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=1200&auto=format&fit=crop', features: ['Floating media cabinetry', 'Textured plaster finishes', 'Bespoke seating configurations', 'Integrated gallery display units'] },
        { title: 'Office Interiors', tag: 'Refined Workspaces', desc: 'Productive home offices and study spaces that feel sophisticated and focused. We blend modern ergonomic standards with high-end materials like American walnut and anodized aluminum. Hidden cable organizer ducts, custom task lighting, and acoustic felt backing ensure a clean, distraction-free environment.', image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1200&auto=format&fit=crop', features: ['Walnut veneer executive desks', 'Concealed wiring systems', 'Acoustic felt paneling', 'Smart storage & floating shelves'] },
        { title: 'Turnkey Interiors', tag: 'End-to-End Execution', desc: 'A single-source, hassle-free engagement where we handle every stage of your project — from concept and 3D design to procurement, civil works, carpentry, and final handover. One dedicated project manager, one timeline, one accountable team delivering your complete home, move-in ready.', image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=1200&auto=format&fit=crop', features: ['Single-point project ownership', 'Design + civil + execution in-house', 'Dedicated project manager & timeline', 'Move-in ready final handover'] },
        { title: 'Renovation', tag: 'Breathe New Life', desc: 'Transform your existing home without starting from scratch. Our renovation expertise covers structural modifications, layout reconfigurations, bathroom and kitchen makeovers, flooring upgrades, and complete aesthetic overhauls. We assess the existing structure, reinforce where needed, and deliver a refreshed space that feels entirely new.', image: 'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?q=80&w=1200&auto=format&fit=crop', features: ['Structural modifications & layout reconfigurations', 'Kitchen & bathroom makeovers', 'Flooring, tiling & plumbing upgrades', 'Complete aesthetic overhauls & repainting'] }
      ]
    },
    is_visible: true,
    section_order: 1
  },
  {
    page: 'services',
    type: 'pricing',
    title: 'Starting Pricing Guide',
    subtitle: 'TRANSPARENT ESTIMATES',
    description: 'We provide transparent cost estimations up front to align layout goals with material preferences.',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {
      items: [
        { title: 'Modular Kitchen', range: '₹1.5L – ₹5L', desc: 'Starting range for custom layouts, high-moisture resistant plywood, acrylic/laminate shutters, and soft-close hardware.' },
        { title: 'Bedroom Interiors', range: '₹80K – ₹3L', desc: 'Includes custom double bed, master sliding wardrobe with modular internal drawers, bedside units, and mood lighting coves.' },
        { title: 'Living Room Design', range: '₹1L – ₹4L', desc: 'Covers television floating unit, custom wood paneling, wall niches, styling moldings, and built-in storage solutions.' }
      ]
    },
    is_visible: true,
    section_order: 2
  },
  {
    page: 'services',
    type: 'why-choose',
    title: 'Why Homeowners Trust Hayagriva',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: { variant: 'light', heading: 'Why Homeowners Trust Hayagriva' },
    is_visible: true,
    section_order: 3
  },
  {
    page: 'services',
    type: 'faq',
    title: 'Services & Pricing Questions',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: { variant: 'cream', items: SERVICES_FAQS },
    is_visible: true,
    section_order: 4
  }
]

export const CONTACT_SECTIONS = [
  {
    page: 'contact',
    type: 'contact',
    title: 'Start Your Design Journey',
    subtitle: 'Get In Touch',
    description: 'Book a complimentary design consultation at our studio or schedule a call with our lead designers.',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {
      intro: 'Drop by our studio for a cup of coffee and browse our extensive catalog of material samples, woods, and upholstery fabrics.',
      mapUrl: 'https://www.google.com/maps/search/?api=1&query=Hayagriva%20Interiors%2C%20Maddilapalem%2C%20Visakhapatnam',
      contactItems: [
        { icon: 'MapPin', label: 'Our Studio', value: 'second floor, DR DEEN COMPLEX, 51-15-1/6, opposite to Tech Mahindra, Satyam Junction, KRANTHI NAGAR, Maddilapalem, Visakhapatnam, Andhra Pradesh 530013' },
        { icon: 'Phone', label: 'Phone Call', value: '+91 95731 78887', href: 'tel:+919573178887', subtext: 'Mon-Sat, 9:30 AM - 7:00 PM' },
        { icon: 'Mail', label: 'Email Address', value: 'interiorsbyhayagriva@gmail.com', href: 'mailto:interiorsbyhayagriva@gmail.com' },
        { icon: 'Clock', label: 'Consultation Hours', value: '9AM to 7PM' }
      ]
    },
    is_visible: true,
    section_order: 0
  },
  {
    page: 'contact',
    type: 'why-choose',
    title: 'Why Homeowners Trust Hayagriva',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: { variant: 'light', heading: 'Why Homeowners Trust Hayagriva' },
    is_visible: true,
    section_order: 1
  },
  {
    page: 'contact',
    type: 'faq',
    title: 'Visiting & Contacting Us',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: { variant: 'cream', items: CONTACT_FAQS },
    is_visible: true,
    section_order: 2
  }
]

export const PORTFOLIO_SECTIONS = [
  {
    page: 'portfolio',
    type: 'hero',
    title: 'Our Projects',
    subtitle: 'Portfolio Collection',
    description: 'Explore a curated gallery of kitchen, bedroom, and living room transformations with rich imagery, smooth interactions, and immersive details.',
    layout: 'split',
    images: [{ url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=1200&auto=format&fit=crop' }],
    buttons: [],
    custom_json: {
      showLeadForm: false
    },
    is_visible: true,
    section_order: 0
  },
  {
    page: 'portfolio',
    type: 'portfolio-grid',
    title: '',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {
      categories: ['All', 'Kitchen', 'Bedroom', 'Living Room']
    },
    is_visible: true,
    section_order: 1
  },
  {
    page: 'portfolio',
    type: 'before-after',
    title: 'The Art of Metamorphosis',
    subtitle: 'Visual Transformation',
    description: 'Drag the center slider handle to compare an empty measurement shell structure with our finalized bespoke turnkey layout.',
    layout: 'full-width',
    images: [
      { url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=1200&auto=format&fit=crop', label: 'Before: Empty Shell Structure' },
      { url: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?q=80&w=1200&auto=format&fit=crop', label: 'After: Finished Luxury Suite' }
    ],
    buttons: [],
    custom_json: {
      beforeLabel: 'Before: Empty Shell Structure',
      afterLabel: 'After: Finished Luxury Suite'
    },
    is_visible: true,
    section_order: 2
  },
  {
    page: 'portfolio',
    type: 'craft-standards',
    title: 'Our Studio Standards',
    subtitle: 'Bespoke Engineering',
    description: 'We focus on material integrity and everyday ergonomics, engineering high-end environments built to last.',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {
      items: [
        { title: 'Precision Joinery', desc: 'Matte lacquered MDF panels, natural white oak veneers, and premium soft-close runners engineered for seamless daily luxury.', icon: 'Layers' },
        { title: 'Lighting Integration', desc: 'Concealed warm LED diffusers, custom task lights, and smart dimming spots built to sculpt and transition spatial mood.', icon: 'Lightbulb' },
        { title: 'Material Honesty', desc: 'Selected Calacatta marble slabs, hand-plastered textured walls, and brushed brass details designed to age beautifully.', icon: 'Hammer' }
      ]
    },
    is_visible: true,
    section_order: 3
  },
  {
    page: 'portfolio',
    type: 'why-choose',
    title: 'Why Homeowners Trust Hayagriva',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: { variant: 'light', heading: 'Why Homeowners Trust Hayagriva' },
    is_visible: true,
    section_order: 4
  },
  {
    page: 'portfolio',
    type: 'faq',
    title: 'Portfolio Questions, Answered',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: { variant: 'cream', items: PORTFOLIO_FAQS },
    is_visible: true,
    section_order: 5
  },
  {
    page: 'portfolio',
    type: 'cta',
    title: 'Ready to Design Your Haven?',
    subtitle: 'Design Consultation',
    description: 'Schedule a design session with our principal architects. We will discuss spatial blueprints, sample material palettes, and immediately compute customized site estimates.',
    layout: 'full-width',
    images: [],
    buttons: [{ text: 'Book Consultation', link: '/contact' }],
    custom_json: { variant: 'full' },
    is_visible: true,
    section_order: 6
  }
]

/** All sections merged for the seed script. */
export const ALL_SECTIONS = [
  ...HOME_SECTIONS,
  ...ABOUT_SECTIONS,
  ...SERVICES_SECTIONS,
  ...CONTACT_SECTIONS,
  ...PORTFOLIO_SECTIONS
]

/** Pages managed by the seed script (cleared & re-seeded). */
export const SEEDED_PAGES = ['home', 'about', 'services', 'contact', 'portfolio']
