// ── Seed data ────────────────────────────────────────────────────
//
// Exact transcription of every hardcoded section from:
//   app/home-view.jsx      (11 sections)
//   app/about/about-view.jsx (6 sections)
//   app/services/services-view.jsx (6 sections)
//   app/contact/contact-view.jsx (3 sections)
//
// Each entry is a page_sections row minus id/timestamps (generated by seed script).
// The script (scripts/seed-sections.mjs) reads this, clears existing rows for
// these pages, and inserts them fresh — idempotent.

export const HOME_SECTIONS = [
  {
    page: 'home',
    type: 'hero',
    title: 'Transform Your Home into a',
    subtitle: 'Luxury Turnkey Interiors',
    description: 'Bespoke layouts, premium materials, and flawless execution. We translate your story into tailored residential sanctuaries.',
    layout: 'full-width',
    images: [],
    buttons: [
      { text: 'Book Free Consultation', link: '#consultation' },
      { text: 'View Portfolio', link: '/portfolio' }
    ],
    custom_json: {
      titleAccent: 'Dream Space.',
      showLeadForm: true
    },
    is_visible: true,
    section_order: 0
  },
  {
    page: 'home',
    type: 'stats',
    title: '',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {
      items: [
        { value: 500, suffix: '+', label: 'Homes Delivered', subtext: 'Exquisite designs across AP', icon: 'CheckCircle2' },
        { value: 5, suffix: '+ Years', label: 'Experience', subtext: 'Refined craftsmanship', icon: 'Shield' },
        { value: 100, suffix: '%', label: 'Client Satisfaction', subtext: 'Discerning reviews', icon: 'Heart' }
      ]
    },
    is_visible: true,
    section_order: 1
  },
  {
    page: 'home',
    type: 'services-preview',
    title: 'Services We Specialize In',
    subtitle: 'Expert Design Studios',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {
      viewAllLink: '/services',
      items: [
        { title: 'Modular Kitchen', desc: 'Sleek, ergonomic layouts featuring premium soft-close cabinets, white oak paneling, and marble surfaces.', icon: 'Utensils', href: '/services/modular-kitchen' },
        { title: 'Bedroom Interiors', desc: 'Timeless master suites designed for peace. Custom headboards, walk-in closets, and ambient bedside lighting.', icon: 'Bed', href: '/services/bedroom' },
        { title: 'Living Room Design', desc: 'Elegant lounges blending Scandinavian simplicity and luxury. Floating media consoles and bespoke plaster walls.', icon: 'Sofa', href: '/services/living-room' },
        { title: 'Space Planning & 3D Design', desc: 'Professional space planning with photorealistic 3D renders to visualize your home before a single material is ordered.', icon: 'PencilRuler', href: '/services/space-planning' },
        { title: 'Turnkey Interiors', desc: 'Complete interior solutions from design to execution.', icon: 'KeyRound', href: '/services/turnkey-solutions' },
        { title: 'Renovation', desc: 'Revitalize your existing spaces with expert remodeling, structural upgrades, and aesthetic makeovers.', icon: 'Hammer', href: '/services/renovation' }
      ]
    },
    is_visible: true,
    section_order: 2
  },
  {
    page: 'home',
    type: 'process-timeline',
    title: 'Our Seamless Design Process',
    subtitle: 'The Turnkey Workflow',
    description: 'A refined, transparent journey from the first conversation to the final handover — crafted with care at every step.',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {
      steps: [
        { step: '01', title: 'Consultation', desc: 'We understand your needs, space, and budget to craft a clear vision for your project.', icon: 'ClipboardList' },
        { step: '02', title: 'Design & Planning', desc: 'We create detailed layouts, 3D designs, and execution-ready plans tailored to you.', icon: 'PencilRuler' },
        { step: '03', title: 'Material Selection', desc: 'Choose premium finishes, colors, and materials that match your aesthetic perfectly.', icon: 'Palette' },
        { step: '04', title: 'Execution', desc: 'Our skilled craftsmen bring the design to life with precision and supervision.', icon: 'Hammer' },
        { step: '05', title: 'Handover', desc: 'Final delivery with rigorous quality assurance and a flawless, ready-to-live space.', icon: 'KeyRound' }
      ],
      highlights: [
        { title: 'On-Time Delivery', desc: 'Projects delivered as promised', icon: 'Clock' },
        { title: 'Quality Assurance', desc: 'Rigorous checks at every stage', icon: 'ShieldCheck' },
        { title: 'Expert Team', desc: 'Skilled designers & craftsmen', icon: 'Users' },
        { title: 'End-to-End Support', desc: 'With you from concept to handover', icon: 'Headphones' }
      ]
    },
    is_visible: true,
    section_order: 3
  },
  {
    page: 'home',
    type: 'before-after',
    title: 'Witness the Difference',
    subtitle: 'Visual Transformation',
    description: 'Drag the center slider handle left or right to compare a raw site measurement shell with our finalized bespoke interior.',
    layout: 'full-width',
    images: [
      { url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=1200&auto=format&fit=crop', label: 'Before: Empty space shell' },
      { url: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?q=80&w=1200&auto=format&fit=crop', label: 'After: Luxury Bed Chamber' }
    ],
    buttons: [],
    custom_json: {},
    is_visible: true,
    section_order: 4
  },
  {
    page: 'home',
    type: 'room-designs',
    title: 'Room-wise Inspirations',
    subtitle: 'Aesthetics by Room',
    description: 'Explore custom catalogs designed specifically for each room environment. Select a room below to filter our selected creations.',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {
      items: [
        { name: 'Kitchen', image: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?q=80&w=800&auto=format&fit=crop', filter: 'Kitchen', tag: 'Culinary Hubs' },
        { name: 'Bedroom', image: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?q=80&w=800&auto=format&fit=crop', filter: 'Bedroom', tag: 'Serene Sanctuary' },
        { name: 'Living Room', image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=800&auto=format&fit=crop', filter: 'Living Room', tag: 'Grand Lounge' }
      ]
    },
    is_visible: true,
    section_order: 5
  },
  {
    page: 'home',
    type: 'testimonials',
    title: 'What Our Clients Say',
    subtitle: 'Google Reviews',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {},
    is_visible: true,
    section_order: 6
  },
  {
    page: 'home',
    type: 'featured-projects',
    title: 'Selected Creations',
    subtitle: 'Portfolio Highlights',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {
      viewAllLink: '/portfolio',
      items: [
        { title: 'Modern Wood Kitchen & Island', type: 'Modular Kitchen', budget: '₹8.5 Lakhs', image: '/images/project-1.jpg', category: 'Kitchen', desc: 'Fine timber panels, bespoke configurations, custom layout styling.' },
        { title: 'Bespoke Master Wardrobe', type: 'Residential Fitout', budget: '₹12 Lakhs', image: '/images/project-2.jpg', category: 'Bedroom', desc: 'Fine timber panels, bespoke configurations, custom layout styling.' },
        { title: 'Japandi Living Lounge', type: 'Full Residence', budget: '₹22 Lakhs', image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=800&auto=format&fit=crop', category: 'Living Room', desc: 'Fine timber panels, bespoke configurations, custom layout styling.' }
      ]
    },
    is_visible: true,
    section_order: 7
  },
  {
    page: 'home',
    type: 'why-choose',
    title: 'Why Homeowners Trust Hayagriva',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: { variant: 'light', heading: 'Why Homeowners Trust Hayagriva' },
    is_visible: true,
    section_order: 8
  },
  {
    page: 'home',
    type: 'faq',
    title: 'Your Interior Design Questions, Answered',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: { faqSet: 'home', variant: 'cream', heading: 'Your Interior Design Questions, Answered' },
    is_visible: true,
    section_order: 9
  },
  {
    page: 'home',
    type: 'cta',
    title: 'Ready to Transform Your Space?',
    subtitle: 'Design Consultation',
    description: 'Schedule a complimentary design session with our lead architects. We will prepare space blueprints, select material samples, and provide immediate project estimates.',
    layout: 'full-width',
    images: [],
    buttons: [{ text: 'Get Free Quote', link: '/contact' }],
    custom_json: { variant: 'full' },
    is_visible: true,
    section_order: 10
  }
]

export const ABOUT_SECTIONS = [
  {
    page: 'about',
    type: 'hero',
    title: 'Elegance, Craft, and a Signature',
    subtitle: 'Hayagriva Studio',
    description: 'We design luxury interiors that feel warm, modern, and deeply personal. Every residential project is built to reflect your story, with thoughtful layout details, premium finishes, and turnkey timeline execution.',
    layout: 'split',
    images: [{ url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=1200&auto=format&fit=crop', key: '' }],
    buttons: [
      { text: 'Work With Us', link: '/contact' },
      { text: 'View Portfolio', link: '/portfolio' }
    ],
    custom_json: {
      titleAccent: 'Design Approach.',
      showLeadForm: false
    },
    is_visible: true,
    section_order: 0
  },
  {
    page: 'about',
    type: 'about-story',
    title: 'A boutique studio rooted in craftsmanship, layout optimization, and material honesty.',
    subtitle: 'OUR JOURNEY',
    description: 'Hayagriva Interiors began with a desire to create residential sanctuaries that feel curated, calm, and unmistakably premium. We blend modern architecture with bespoke joinery, delivering homes that balance luxury with livability.\n\nOur approach is highly collaborative: we listen deeply to your spatial habits, draft precise plans, and oversee manufacture so the final result is both beautiful and built to last.',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {
      cards: [
        { label: 'MISSION', heading: 'Design homes that feel personal and timeless.', body: 'We create residential environments that elevate everyday rituals through intelligent layout configurations, layered lighting, and elegant joinery.' },
        { label: 'VISION', heading: 'The first choice for luxurious residential interiors.', body: 'We aspire to define new standards of premium home design across the region with every project we deliver, from conceptual sketches to key handover.' }
      ]
    },
    is_visible: true,
    section_order: 1
  },
  {
    page: 'about',
    type: 'why-choose',
    title: 'The Trusted Choice for Discerning Homeowners',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: { variant: 'light', heading: 'The Trusted Choice for Discerning Homeowners' },
    is_visible: true,
    section_order: 2
  },
  {
    page: 'about',
    type: 'design-journal',
    title: 'Bespoke Interior Insights',
    subtitle: 'DESIGN JOURNAL',
    description: "Read our principal designers' guides on material selections, layouts, lighting, and styling aesthetics.",
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {
      items: [
        { title: 'The Art of Japandi Minimalist Living', category: 'Aesthetics', date: 'June 12, 2026', image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=800&auto=format&fit=crop', desc: 'Discover how to balance raw Scandinavian warmth with quiet Japanese simplicity to create an uncluttered, modern sanctuary.', slug: 'art-of-japandi-minimalist-living' },
        { title: 'Ergonomic Modular Kitchen Guidelines', category: 'Engineering', date: 'May 28, 2026', image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop', desc: 'An in-depth look at counter heights, modular layout workflows, soft-close hardware configurations, and material selections.', slug: 'ergonomic-modular-kitchen-guidelines' },
        { title: 'Layered Illumination for Private Suites', category: 'Lighting', date: 'April 15, 2026', image: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?q=80&w=800&auto=format&fit=crop', desc: 'How to configure layered bedroom lighting using concealed warm coves, task spots, and smart dimming transitions.', slug: 'layered-illumination-private-suites' }
      ]
    },
    is_visible: true,
    section_order: 3
  },
  {
    page: 'about',
    type: 'faq',
    title: 'About Hayagriva Interiors',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: { faqSet: 'about', variant: 'cream', heading: 'About Hayagriva Interiors' },
    is_visible: true,
    section_order: 4
  },
  {
    page: 'about',
    type: 'cta',
    title: 'Ready to Design Your Haven?',
    subtitle: 'Design Consultation',
    description: 'Schedule a design session with our principal architects. We will discuss spatial blueprints, sample material palettes, and immediately compute customized site estimates.',
    layout: 'full-width',
    images: [],
    buttons: [{ text: 'Book Consultation', link: '/contact' }],
    custom_json: { variant: 'rounded' },
    is_visible: true,
    section_order: 5
  }
]

export const SERVICES_SECTIONS = [
  {
    page: 'services',
    type: 'services-grid',
    title: 'Curated Solutions for Your Home',
    subtitle: 'DESIGN SPECIALTIES',
    description: 'Click to explore room layouts designed to match your individual standard of daily comfort and luxurious spacing.',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {
      items: [
        { title: 'Modular Kitchen', desc: 'Precision cabinetry, natural stone countertops, and intelligent storage layouts.', image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=1000&auto=format&fit=crop', slug: 'modular-kitchen', filter: 'Kitchen' },
        { title: 'Bedroom Interiors', desc: 'Calm suites with luxury headboards, custom walk-in closets, and ambient lighting.', image: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?q=80&w=1000&auto=format&fit=crop', slug: 'bedroom', filter: 'Bedroom' },
        { title: 'Living Room Design', desc: 'Elegant lounges blending tailored furniture, floating consoles, and custom walls.', image: 'https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?q=80&w=1000&auto=format&fit=crop', slug: 'living-room', filter: 'Living Room' },
        { title: 'Space Planning & 3D Design', desc: 'Professional layouts with photorealistic renders before construction begins.', image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=1000&auto=format&fit=crop', slug: 'space-planning', filter: '' },
        { title: 'Turnkey Interiors', desc: 'Complete interior solutions from design to execution.', image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=1000&auto=format&fit=crop', slug: 'turnkey-solutions', filter: '' },
        { title: 'Renovation', desc: 'Revitalize your existing spaces with expert remodeling and structural upgrades.', image: 'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?q=80&w=1000&auto=format&fit=crop', slug: 'renovation', filter: '' }
      ]
    },
    is_visible: true,
    section_order: 0
  },
  {
    page: 'services',
    type: 'detailed-services',
    title: '',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {
      items: [
        { title: 'Modular Kitchen', tag: 'Culinary Engineering', desc: 'A high-performance kitchen designed around your workflow. We build custom modular setups incorporating premium soft-close drawer tracks, heavy-duty pull-out trays, and natural quartz countertops. Every cabinet and cabinet front is engineered to withstand daily use while presenting an immaculate, handleless aesthetic.', image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop', features: ['Custom modular layouts', 'Quartz & marble counters', 'Soft-close hardware', 'Under-cabinet illumination'] },
        { title: 'Bedroom Interiors', tag: 'Serene Sanctuaries', desc: 'Transform your bedroom into a quiet retreat. Our designers custom craft floor-to-ceiling headboards, integrated floating nightstands, and walk-in wardrobe organizers with matte finishes. Lighting is layered seamlessly using dimmable LED coves and directional task spotlights to transition spatial mood effortlessly.', image: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?q=80&w=1200&auto=format&fit=crop', features: ['Ergonomic wardrobe systems', 'Custom upholstered headboards', 'Layered mood coves', 'Space-optimizing layouts'] },
        { title: 'Living Room Design', tag: 'Grand Entertainment Lounges', desc: 'Bespoke living environments made for social gathering and quiet comfort alike. We specialize in floating entertainment consoles, wood-paneled feature walls, and hand-plastered textured finishes. Every piece of furniture is scaled and positioned to optimize both architectural flow and everyday comfort.', image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=1200&auto=format&fit=crop', features: ['Floating media cabinetry', 'Textured plaster finishes', 'Bespoke seating configurations', 'Integrated gallery display units'] },
        { title: 'Office Interiors', tag: 'Refined Workspaces', desc: 'Productive home offices and study spaces that feel sophisticated and focused. We blend modern ergonomic standards with high-end materials like American walnut and anodized aluminum. Hidden cable organizer ducts, custom task lighting, and acoustic felt backing ensure a clean, distraction-free environment.', image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1200&auto=format&fit=crop', features: ['Walnut veneer executive desks', 'Concealed wiring systems', 'Acoustic felt paneling', 'Smart storage & floating shelves'] },
        { title: 'Turnkey Interiors', tag: 'End-to-End Execution', desc: 'A single-source, hassle-free engagement where we handle every stage of your project — from concept and 3D design to procurement, civil works, carpentry, and final handover. One dedicated project manager, one timeline, one accountable team delivering your complete home, move-in ready.', image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=1200&auto=format&fit=crop', features: ['Single-point project ownership', 'Design + civil + execution in-house', 'Dedicated project manager & timeline', 'Move-in ready final handover'] },
        { title: 'Renovation', tag: 'Breathe New Life', desc: 'Transform your existing home without starting from scratch. Our renovation expertise covers structural modifications, layout reconfigurations, bathroom and kitchen makeovers, flooring upgrades, and complete aesthetic overhauls. We assess the existing structure, reinforce where needed, and deliver a refreshed space that feels entirely new.', image: 'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?q=80&w=1200&auto=format&fit=crop', features: ['Structural modifications & layout reconfigurations', 'Kitchen & bathroom makeovers', 'Flooring, tiling & plumbing upgrades', 'Complete aesthetic overhauls & repainting'] }
      ]
    },
    is_visible: true,
    section_order: 1
  },
  {
    page: 'services',
    type: 'pricing',
    title: 'Starting Pricing Guide',
    subtitle: 'TRANSPARENT ESTIMATES',
    description: 'We provide transparent cost estimations up front to align layout goals with material preferences.',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {
      items: [
        { title: 'Modular Kitchen', range: '₹1.5L – ₹5L', desc: 'Starting range for custom layouts, high-moisture resistant plywood, acrylic/laminate shutters, and soft-close hardware.' },
        { title: 'Bedroom Interiors', range: '₹80K – ₹3L', desc: 'Includes custom double bed, master sliding wardrobe with modular internal drawers, bedside units, and mood lighting coves.' },
        { title: 'Living Room Design', range: '₹1L – ₹4L', desc: 'Covers television floating unit, custom wood paneling, wall niches, styling moldings, and built-in storage solutions.' }
      ]
    },
    is_visible: true,
    section_order: 2
  },
  {
    page: 'services',
    type: 'why-choose',
    title: 'Why Homeowners Trust Hayagriva',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: { variant: 'light', heading: 'Why Homeowners Trust Hayagriva' },
    is_visible: true,
    section_order: 3
  },
  {
    page: 'services',
    type: 'faq',
    title: 'Services & Pricing Questions',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: { faqSet: 'services', variant: 'cream', heading: 'Services & Pricing Questions' },
    is_visible: true,
    section_order: 4
  }
]

export const CONTACT_SECTIONS = [
  {
    page: 'contact',
    type: 'contact',
    title: 'Start Your Design Journey',
    subtitle: 'Get In Touch',
    description: 'Book a complimentary design consultation at our studio or schedule a call with our lead designers.',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {},
    is_visible: true,
    section_order: 0
  },
  {
    page: 'contact',
    type: 'why-choose',
    title: 'Why Homeowners Trust Hayagriva',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: { variant: 'light', heading: 'Why Homeowners Trust Hayagriva' },
    is_visible: true,
    section_order: 1
  },
  {
    page: 'contact',
    type: 'faq',
    title: 'Visiting & Contacting Us',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: { faqSet: 'contact', variant: 'cream', heading: 'Visiting & Contacting Us' },
    is_visible: true,
    section_order: 2
  }
]

export const PORTFOLIO_SECTIONS = [
  {
    page: 'portfolio',
    type: 'hero',
    title: 'Our Projects',
    subtitle: 'Portfolio Collection',
    description: 'Explore a curated gallery of kitchen, bedroom, and living room transformations with rich imagery, smooth interactions, and immersive details.',
    layout: 'split',
    images: [],
    buttons: [],
    custom_json: {
      showLeadForm: false,
      bgImage: ''
    },
    is_visible: true,
    section_order: 0
  },
  {
    page: 'portfolio',
    type: 'portfolio-grid',
    title: '',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {
      categories: ['All', 'Kitchen', 'Bedroom', 'Living Room']
    },
    is_visible: true,
    section_order: 1
  },
  {
    page: 'portfolio',
    type: 'before-after',
    title: 'The Art of Metamorphosis',
    subtitle: 'Visual Transformation',
    description: 'Drag the center slider handle to compare an empty measurement shell structure with our finalized bespoke turnkey layout.',
    layout: 'full-width',
    images: [
      { url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=1200&auto=format&fit=crop', label: 'Before: Empty Shell Structure' },
      { url: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?q=80&w=1200&auto=format&fit=crop', label: 'After: Finished Luxury Suite' }
    ],
    buttons: [],
    custom_json: {},
    is_visible: true,
    section_order: 2
  },
  {
    page: 'portfolio',
    type: 'craft-standards',
    title: 'Our Studio Standards',
    subtitle: 'Bespoke Engineering',
    description: 'We focus on material integrity and everyday ergonomics, engineering high-end environments built to last.',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: {
      items: [
        { title: 'Precision Joinery', desc: 'Matte lacquered MDF panels, natural white oak veneers, and premium soft-close runners engineered for seamless daily luxury.', icon: 'Layers' },
        { title: 'Lighting Integration', desc: 'Concealed warm LED diffusers, custom task lights, and smart dimming spots built to sculpt and transition spatial mood.', icon: 'Lightbulb' },
        { title: 'Material Honesty', desc: 'Selected Calacatta marble slabs, hand-plastered textured walls, and brushed brass details designed to age beautifully.', icon: 'Hammer' }
      ]
    },
    is_visible: true,
    section_order: 3
  },
  {
    page: 'portfolio',
    type: 'why-choose',
    title: 'Why Homeowners Trust Hayagriva',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: { variant: 'light', heading: 'Why Homeowners Trust Hayagriva' },
    is_visible: true,
    section_order: 4
  },
  {
    page: 'portfolio',
    type: 'faq',
    title: 'Portfolio Questions, Answered',
    subtitle: '',
    description: '',
    layout: 'full-width',
    images: [],
    buttons: [],
    custom_json: { faqSet: 'portfolio', variant: 'cream', heading: 'Portfolio Questions, Answered' },
    is_visible: true,
    section_order: 5
  },
  {
    page: 'portfolio',
    type: 'cta',
    title: 'Ready to Design Your Haven?',
    subtitle: 'Design Consultation',
    description: 'Schedule a design session with our principal architects. We will discuss spatial blueprints, sample material palettes, and immediately compute customized site estimates.',
    layout: 'full-width',
    images: [],
    buttons: [{ text: 'Book Consultation', link: '/contact' }],
    custom_json: { variant: 'full' },
    is_visible: true,
    section_order: 6
  }
]

/** All sections merged for the seed script. */
export const ALL_SECTIONS = [
  ...HOME_SECTIONS,
  ...ABOUT_SECTIONS,
  ...SERVICES_SECTIONS,
  ...CONTACT_SECTIONS,
  ...PORTFOLIO_SECTIONS
]

/** Pages managed by the seed script (cleared & re-seeded). */
export const SEEDED_PAGES = ['home', 'about', 'services', 'contact', 'portfolio']
